name: Check Changesets

on:
  pull_request:
    branches:
      - main

jobs:
  check_changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # Version of pnpm to install
          version: latest # optional
          # Where to store pnpm files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: true # optional, default is null

      - name: Check for changesets
        uses: changesets/action@v1
        with:
          # check if there are any changesets
          check: true
