# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish packages to NPM(Latest)

on:
  workflow_dispatch:
    # inputs:
    #   versionUp:
    #     description: 'Version Up Strage'
    #     required: true
    #     default: 'patch'
    #     type: choice
    #     options:
    #       - patch
    #       - minor
    #       - major
env:
  TONCENTER_TESTNET_API_KEY: ${{ secrets.TONCENTER_TESTNET_API_KEY }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # Version of pnpm to install
          version: latest # optional
          # Where to store pnpm files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: true # optional, default is null

      - name: Build
        run: pnpm build

      - name: Git Identity
        run: |
          git config --global user.name 'hstarorg'
          git config --global user.email 'hm910705@163.com'

      - name: Publish
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          publish: pnpm run pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}
