# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v4
        with:
          # Version of pnpm to install
          version: latest # optional
          # Where to store pnpm files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: true # optional, default is null

      - run: pnpm test
